// Sample Grad-CAM overlay images for demonstration
// In a real implementation, these would be generated by the actual Grad-CAM algorithm

export const gradcamSampleImages = {
  normal: {
    originalImage: '/datasets/mri/NonDemented/nonDem2540.jpg',
    overlayImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', // Placeholder
    description: 'Normal brain with minimal attention areas'
  },
  mci: {
    originalImage: '/datasets/mri/VeryMildDemented/verymildDem1776.jpg',
    overlayImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', // Placeholder
    description: 'MCI brain with moderate attention on hippocampus'
  },
  mild: {
    originalImage: '/datasets/mri/MildDemented/mildDem701.jpg',
    overlayImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', // Placeholder
    description: 'Mild AD with high attention on multiple regions'
  },
  moderate: {
    originalImage: '/datasets/mri/ModerateDemented/moderateDem36.jpg',
    overlayImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', // Placeholder
    description: 'Moderate AD with critical attention across regions'
  }
}

// Generate a sample Grad-CAM overlay based on prediction class
export function getSampleGradCAMImage(predictionClass: string): string {
  const classKey = predictionClass.toLowerCase().replace(/\s+/g, '').replace('ad', '')
  
  switch (classKey) {
    case 'normal':
      return gradcamSampleImages.normal.originalImage
    case 'mci':
      return gradcamSampleImages.mci.originalImage
    case 'mild':
      return gradcamSampleImages.mild.originalImage
    case 'moderate':
      return gradcamSampleImages.moderate.originalImage
    default:
      return gradcamSampleImages.normal.originalImage
  }
}